name: 'Recipe Frontend App'

on:
    push:
        branches:
            - master
            - Feature/react-query

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: 'Setup Node JS'
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: 'Check Node JS Version'
              run: node --version

            - name: 'Clone Repository'
              uses: actions/checkout@v2

            - name: 'list directory'
              run: ls

            - name: 'Install dependencies'
              run: npm install

            - name: 'list directory'
              run: ls

            - name: 'lint test'
              run: npm run lint

            - name: 'Run build'
              run: npm run build

            - name: 'Upload artifacts to be used for deployment'
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: ./dist

            - name: Notify completion
              run: echo "Recipe Frontend App completed"
